#lang racket

(define (make-account balance password attempts)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define call-the-cops
    (lambda (x)
      (error "Incorrect password! Exhausted trials!" attempts)))
  (define (dispatch attempt-pw m)
    (cond ((eq? password attempt-pw)
           (cond ((eq? m 'withdraw) withdraw)
                 ((eq? m 'deposit) deposit)
                 (else (error "Unknown request: MAKE-ACCOUNT" m))))
          ((= attempts 0) call-the-cops)
          (else (begin (set! attempts (- attempts 1))
                       (lambda (x)
                         (format "Incorrect password! You have ~a trials!" attempts))))))
  dispatch)
